"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 5000
format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$line_break$character"""

palette = 'kanagawa_wave'

[palettes.kanagawa_wave]
color_fg0 = '#dcd7ba'
color_fg1 = '#1F1F28'
color_fg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#7e9cd8'
color_green = '#98bb6c'
color_orange = '#e6c384'
color_purple = '#7fb4ca'
color_red = '#e82424'
color_yellow = '#dcd7ba'

[os]
disabled = false
style = "fg:color_fg3"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:color_fg0"
style_root = "fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:color_aqua)]($style)'


[git_status]
format = '[[($all_status$ahead_behind )](fg:color_aqua)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[golang]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[php]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[java]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[python]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[docker_context]
symbol = ""
format = '[[ $symbol( $context) ](fg:#83a598)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:color_fg0)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
