--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/wallpapers/99842.png"

-- Special
background="#101322"
foreground="#e2caca"
cursor="#e2caca"

-- Colors
color0="#101322"
color1="#716779"
color2="#89647C"
color3="#7A6A84"
color4="#8D748B"
color5="#AC7789"
color6="#AA909D"
color7="#e2caca"
color8="#9e8d8d"
color9="#716779"
color10="#89647C"
color11="#7A6A84"
color12="#8D748B"
color13="#AC7789"
color14="#AA909D"
color15="#e2caca"
