# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/wallpapers/j3mv3q.png'

# Special
background='#0a0c16'
foreground='#cacddd'
cursor='#cacddd'

# Colors
color0='#0a0c16'
color1='#3B508B'
color2='#676E93'
color3='#A1648D'
color4='#7887B2'
color5='#7890C4'
color6='#9A97AC'
color7='#cacddd'
color8='#8d8f9a'
color9='#3B508B'
color10='#676E93'
color11='#A1648D'
color12='#7887B2'
color13='#7890C4'
color14='#9A97AC'
color15='#cacddd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
