--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/wallpapers/wqz2or.png"

-- Special
background="#1d2731"
foreground="#c7bbbe"
cursor="#c7bbbe"

-- Colors
color0="#1d2731"
color1="#C18E78"
color2="#596C86"
color3="#6A748D"
color4="#8C7987"
color5="#A27E82"
color6="#7187A1"
color7="#c7bbbe"
color8="#8b8285"
color9="#C18E78"
color10="#596C86"
color11="#6A748D"
color12="#8C7987"
color13="#A27E82"
color14="#7187A1"
color15="#c7bbbe"
