# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/wallpapers/99842.png'

# Special
background='#101322'
foreground='#e2caca'
cursor='#e2caca'

# Colors
color0='#101322'
color1='#716779'
color2='#89647C'
color3='#7A6A84'
color4='#8D748B'
color5='#AC7789'
color6='#AA909D'
color7='#e2caca'
color8='#9e8d8d'
color9='#716779'
color10='#89647C'
color11='#7A6A84'
color12='#8D748B'
color13='#AC7789'
color14='#AA909D'
color15='#e2caca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
