# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/wallpapers/sleepy_mountains_light_v04.png'

# Special
background='#09040a'
foreground='#ead7c8'
cursor='#ead7c8'

# Colors
color0='#09040a'
color1='#D77952'
color2='#BA8575'
color3='#D79E76'
color4='#BE8E81'
color5='#D5AD91'
color6='#DAB095'
color7='#ead7c8'
color8='#a3968c'
color9='#D77952'
color10='#BA8575'
color11='#D79E76'
color12='#BE8E81'
color13='#D5AD91'
color14='#DAB095'
color15='#ead7c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
