 [colors]
        ansi = [
          '#1b1a1c',
          '#505369',
          '#6D6977',
          '#92513E',
          '#9A7263',
          '#9C8177',
          '#757282',
          '#bab4b7',
        ]
        background = '#1b1a1c'
        brights = [
          '#827d80',
          '#505369',
          '#6D6977',
          '#92513E',
          '#9A7263',
          '#9C8177',
          '#757282',
          '#bab4b7',
        ]
        cursor_bg = '#1b1a1c'
        cursor_border = '#bab4b7'
        cursor_fg = '#bab4b7'
        foreground = '#bab4b7'
        selection_bg = '#bab4b7'
        selection_fg = '#1b1a1c'
        [colors.indexed]
        [metadata]
        name = 'Pywal'
        origin_url = 'https://github.com/dylanaraps/pywal'
